# DEV TOOLS
spring:
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true


# LOGGING
logging:
  level:
    com:
      test:
        crypto: DEBUG

bucket4j:
  enabled: true
  filters:
    - cache-name: rate-limit-buckets
      url: /api/.*
      http-response-body: "{ \"status\": 429, \"error\": \"Too Many Requests\", \"message\": \"You have exhausted your API Request Quota\" }"
      rate-limits:
        - cache-key: getRemoteAddr()
          bandwidths:
            - capacity: 5
              time: 5
              unit: minutes


